### ISSUE TITLE
JS errors on checkout

### ISSUE THREAD

**Issue by SilvanLaroo** [afterpay/afterpay-magento-2#1]
Hi, 

I get several JS errors from the Afterpay module on the checkout page. See this attachment: https://www.dropbox.com/s/0pph4faq2niwbjy/screenshot-afterpay-error.png?dl=0. This breaks the checkout page.

**Comment by mcnamee** [comment]
We're also getting JS console errors when using attempting to checkout with Afterpay.

```js
Uncaught SyntaxError: Unexpected token < in JSON at position 79
    at JSON.parse (<anonymous>)
    at Function.jQuery.parseJSON (jquery.js:8517)
    at Function.jQuery.parseJSON (jquery-migrate.js:235)
    at Object.success (afterpaypayovertime.js:102)
    at fire (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at done (jquery.js:9310)
    at XMLHttpRequest.callback (jquery.js:9720)
```

By console.logging the response (where this error occurs in `afterpaypayovertime.js`), I get this:

```js
{"success":true,"token":"123abc"}<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Serialization of 'SplFileInfo' is not allowed' in /files/root/magento2/vendor/magento/framework/Session/SessionManager.php:139
Stack trace:
#0 /files/root/magento2/vendor/magento/framework/Session/SessionManager.php(139): session_write_close()
#1 [internal function]: Magento\Framework\Session\SessionManager-&gt;writeClose()
#2 {main}
  thrown in <b>/files/root/magento2/vendor/magento/framework/Session/SessionManager.php</b> on line <b>139</b><br />
```

Other checkout methods work fine.

**Comment by mcnamee** [comment]
Further information on this:

- We've installed on both the website we intend to use it on as well as a fresh Magento2 install
- We've tried on both Magento v2.1.5 and v2.1.7
- The error appears when the `Payment Action` is set to `Authorise and Capture` (when set to order, it redirects to Afterpay correctly)

**Comment by duytrinhit** [comment]
Hi @mcnamee 
I have fixed your issue by comment the code below in the file
app\code\Afterpay\Afterpay\Controller\Payment\Process.php
//$this->_checkoutSession->setQuote($quote);
Please try and let me know if you have any questions
Thanks

**Comment by mcnamee** [comment]
Hi @duytrinhit 
Yep that works for me - I've tested the full checkout flow with Afterpay as the payment method and the transaction was a success.

Other errors that have came about:

- Mini-cart didn't clear on successful checkout (I've confirmed and on successful checkout with other payment methods, the mini-cart did clear correctly)
- Customer email did not receive order email (I've confirmed and on successful checkout with other payment methods (eg. Paypal), the correct emails sent as expected)

**Comment by stevenocta** [comment]
Hi, 

The function _setQuote_ would be replaced with _replaceQuote()_ on the next releases.
The SPL File Info item should not occur on the future releases.

Thank you very much for bringing this to our attention.
