### ISSUE TITLE
Customer not notified of transaction

### ISSUE THREAD

**Issue by brideo** [afterpay/afterpay-magento-2#3]
No order email is ever sent to the customer, I have created a pull request to fix this. 

https://github.com/afterpay/afterpay-magento-2/pull/2

**Comment by stevenocta** [comment]
Hi, 

Thank you very much for bringing this to our attention.
An improvement on the plugin is currently being developed which would trigger the Order Sender (Magento\Sales\Model\Order\Email\Sender\OrderSender) on the order creation.

**Comment by eharvest** [comment]
I just had the latest AfterPay Update and I still have the same issue on M2.1.9. Is it possible to reopen this?
