### ISSUE TITLE
Adding quote object to the session????

### ISSUE THREAD

**Issue by bgkavinga** [afterpay/afterpay-magento-2#5]
Afterpay/Afterpay/Controller/Payment/Process.php:148 adding quote object to session. If you add something to the session it should be serializable otherwise it will cause errors. Also adding such large object to the session is not acceptable.
What is the purpose of adding Quote object to the session?

I am getting errors due to this issue. 
```
PHP message: PHP Fatal error:  Uncaught Exception: Notice: session_write_close(): &quot;_defaultAttributes&quot; returned as member variable from __sleep() but does not exist in /home/www/snb-loc.ns-staging.com.au/codepool/vendor/magento/framework/Session/SessionManager.php on line 139 in /home/www/snb-loc.ns-staging.com.au/codepool/vendor/magento/framework/App/ErrorHandler.php:61

```

**Comment by stevenocta** [comment]
HI,

Thank you for bringing this to our attention. 
In the next releases the _setQuote()_ will be switched with _replaceQuote()_

The new function (_replaceQuote_) would be replacing the Quote ID instead of writing the quote to the session, therefore avoiding this case.

**Comment by bgkavinga** [comment]
Hi @stevenocta FYI You can not close a ticket without resolving it. Having issue count 0 does not make it perfect.
