### ISSUE TITLE
Module is not compliance with Magento 2 coding standards or best practices.

### ISSUE THREAD

**Issue by bgkavinga** [afterpay/afterpay-magento-2#6]
This module does not follow Magento 2 coding standards or best practices. There are a lot of die statements used to generate ajax responses. Use JsonResultFactory instead.
Use of uninitialized objects.

**Comment by stevenocta** [comment]
Hi,

Thank you very much for bringing to our attention. 
Our team are reviewing this and an improvement would be made on future releases.

**Comment by bgkavinga** [comment]
Hi @stevenocta FYI You can not close a ticket without resolving it. Having issue count 0 does not make it perfect.
