### ISSUE TITLE
separate "order data processing" from main flow

### ISSUE THREAD

**Issue by speedupmate** [afterpay/afterpay-magento-2#9]
https://github.com/afterpay/afterpay-magento-2/blob/c18bbecea4dadd0d6f36b39fa805bf1b5b6d2092/Afterpay/Afterpay/Controller/Payment/Process.php#L71

Afterpay payment method adds a ajax call before place order to request/validate its token , during that process address data is validated from quote object taken from session in 

https://github.com/afterpay/afterpay-magento-2/blob/c18bbecea4dadd0d6f36b39fa805bf1b5b6d2092/Afterpay/Afterpay/Model/Adapter/V1/AfterpayOrderTokenV1.php#L210

Actual order placement takes place in another API endpoint and requests data from other methods. 
The issue is that between those ajax calls a gap exist and address or order data can change between those separate calls:
* either by customer actions in frontend 
* in different UI flow for checkout where address data might be edited after paymentmethod selection or shipping method selection 
* 3rd party extensions manipulating the data with plugins like Afterpay itself is doing on afterSavePaymentInformationAndPlaceOrder call)  and order placement might happen with wrong data 

solution would be to refactor Afterpay to remove this separate controller call and do their validation in beforeSavePaymentInformationAndPlaceOrder to ensure:
* that there is no gap in data request flow and they always use  the same address (or other related data) that magento2 is using on order placement time 
* regular place order error or success flow is used

**Comment by skynixukraine** [comment]
Hi Support,

Does anyone work on this?
